version: "3.8"
   
services:
  server:
    restart: always
    container_name: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './server:/server'
    ports:
      - "8000:8000"
  client:
    restart: always
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: react-scripts start
    volumes:
      - './client:/client'
      - '/client/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true