# Generated by Django 3.2.8 on 2022-01-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
