# Generated by Django 3.2.8 on 2022-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='steamid',
            field=models.CharField(default='000000', max_length=120),
        ),
    ]
