# Generated by Django 3.2.9 on 2022-02-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='steamuser',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='emailsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='weekly_hours',
            field=models.CharField(default='', max_length=255),
        ),
    ]
