# Generated by Django 3.2.9 on 2022-02-27 06:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='daily_hours',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='emailsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='goal',
            field=models.IntegerField(default=40),
        ),
    ]
