# Generated by Django 3.2.8 on 2022-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0002_auto_20220131_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationID', models.CharField(default='null', max_length=50)),
                ('senderID', models.CharField(default='null', max_length=30)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
