# Generated by Django 3.2.8 on 2022-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0002_auto_20220131_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='goal',
            field=models.IntegerField(default=300),
        ),
    ]
