# Generated by Django 3.2.8 on 2022-01-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0002_friendslist_steamid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
