# Generated by Django 3.2.9 on 2022-03-10 10:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0002_auto_20220227_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='achievements',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
