# Generated by Django 3.2.9 on 2022-02-26 01:13

import Kusa.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0003_alter_steamuser_weekly_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='weekly_hours',
            field=djongo.models.fields.ArrayField(model_container=Kusa.models.HoursPlayed, model_form_class=Kusa.models.HoursPlayedForm),
        ),
    ]
