# Generated by Django 3.2.8 on 2022-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0003_steamuser_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='goal',
            field=models.IntegerField(default=40),
        ),
    ]
