# Generated by Django 3.2.8 on 2022-01-24 21:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0004_dummy_gamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='FriendRequest',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
