# Generated by Django 3.2.9 on 2022-02-27 03:16

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0004_auto_20220226_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='weekly_hours',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='daily_hours',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
