# Generated by Django 3.2.9 on 2022-02-26 07:48

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0004_auto_20220226_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='weekly_hours',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
