# Generated by Django 3.2.8 on 2022-01-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0004_alter_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FPS', models.CharField(max_length=30)),
            ],
        ),
    ]
