# Generated by Django 3.2.8 on 2022-01-24 21:47

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0005_dummy_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='null', max_length=30)),
                ('SteamID', models.CharField(default='null', max_length=30)),
                ('FriendList', djongo.models.fields.JSONField(default=[])),
                ('FriendRequest', djongo.models.fields.JSONField(default=[])),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
