# Generated by Django 3.2.8 on 2022-02-16 02:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0006_auto_20220124_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='FavoriteList',
            field=djongo.models.fields.JSONField(default=[]),
        ),
    ]
