# Generated by Django 3.2.8 on 2022-01-30 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kusa', '0006_auto_20220124_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='FriendsRequest',
            new_name='FriendRequest',
        ),
        migrations.AlterField(
            model_name='test',
            name='FriendList',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='test',
            name='FriendRequest',
            field=models.JSONField(default=[]),
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friends', models.ManyToManyField(blank=True, related_name='Friends', to=settings.AUTH_USER_MODEL)),
                ('Gamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Gamer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField(blank=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
