# Generated by Django 3.2.8 on 2022-01-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kusa', '0007_auto_20220129_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='FriendRequest',
            new_name='FriendsRequest',
        ),
    ]
